-- Reviewed baseline for a NEW PostgreSQL database; apply through Flyway/Liquibase in production.
CREATE TABLE products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku varchar(64) NOT NULL,
    name varchar(200) NOT NULL,
    description varchar(2000),
    price numeric(19,2) NOT NULL CHECK (price > 0),
    status varchar(16) NOT NULL CHECK (status IN ('ACTIVE','INACTIVE','DELETED')),
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT uk_product_sku UNIQUE (sku)
);
CREATE TABLE inventory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL,
    total_quantity integer NOT NULL,
    reserved_quantity integer NOT NULL,
    version bigint NOT NULL DEFAULT 0,
    updated_at timestamp NOT NULL,
    CONSTRAINT uk_inventory_product UNIQUE (product_id),
    CONSTRAINT fk_inventory_product FOREIGN KEY (product_id) REFERENCES products(id),
    CONSTRAINT ck_inventory_quantities CHECK (
        total_quantity >= 0 AND reserved_quantity >= 0 AND reserved_quantity <= total_quantity
    )
);
CREATE TABLE inventory_reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL CHECK (order_id > 0),
    product_id bigint NOT NULL,
    quantity integer NOT NULL CHECK (quantity > 0),
    status varchar(16) NOT NULL CHECK (status IN ('RESERVED','CONFIRMED','RELEASED')),
    version bigint NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT uk_reservation_order_product UNIQUE (order_id, product_id),
    CONSTRAINT fk_reservation_product FOREIGN KEY (product_id) REFERENCES products(id)
);
CREATE INDEX ix_reservation_product ON inventory_reservations(product_id);

